# Generated by Django 3.2.6 on 2021-08-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HArcherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateField(default='2021-08-19'),
        ),
        migrations.AlterField(
            model_name='training',
            name='track',
            field=models.CharField(choices=[('1', 'Tower 90'), ('2', 'Tower 110'), ('3', 'Raid 2-3-5'), ('4', 'Raid 2-3-3')], max_length=1),
        ),
    ]
