# Generated by Django 3.2.6 on 2021-08-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HArcherApp', '0002_auto_20210819_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='title',
            field=models.CharField(default='Trening', max_length=64),
        ),
    ]
