# Generated by Django 3.2.6 on 2021-08-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HArcherApp', '0005_training_horse'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(default='Brak'),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(default='Tower 90', max_length=64),
        ),
    ]
