# Generated by Django 3.2.6 on 2021-08-29 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HArcherApp', '0006_auto_20210823_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrows_shoot', models.PositiveSmallIntegerField(default='0')),
                ('counted_arrows', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('arrows_in_target_no_points', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('arrows_in_target', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('missed_arrows', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('average_arrow_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('arrows_shoot_f', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('counted_arrows_f', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('average_arrow_score_f', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('arrows_in_target_f', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('arrows_counted_to_no_points_f', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('arrows_in_target_no_points_f', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('missed_arrows_f', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('accuracy_f', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('arrows_shoot_b', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('counted_arrows_b', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('average_arrow_score_b', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('arrows_in_target_b', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('arrows_counted_to_no_points_b', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('arrows_in_target_no_points_b', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('missed_arrows_b', models.PositiveSmallIntegerField(blank=True, default='0', null=True)),
                ('accuracy_b', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='dodatkowe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HArcherApp.results'),
        ),
    ]
