# Generated by Django 3.2.6 on 2021-09-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HArcherApp', '0008_auto_20210829_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='accuracy_b',
        ),
        migrations.RemoveField(
            model_name='training',
            name='accuracy_f',
        ),
        migrations.RemoveField(
            model_name='training',
            name='arrows_counted_to_no_points_b',
        ),
        migrations.RemoveField(
            model_name='training',
            name='arrows_counted_to_no_points_f',
        ),
        migrations.RemoveField(
            model_name='training',
            name='arrows_in_target',
        ),
        migrations.RemoveField(
            model_name='training',
            name='arrows_in_target_b',
        ),
        migrations.RemoveField(
            model_name='training',
            name='arrows_in_target_f',
        ),
        migrations.RemoveField(
            model_name='training',
            name='arrows_in_target_no_points',
        ),
        migrations.RemoveField(
            model_name='training',
            name='arrows_in_target_no_points_b',
        ),
        migrations.RemoveField(
            model_name='training',
            name='arrows_in_target_no_points_f',
        ),
        migrations.RemoveField(
            model_name='training',
            name='arrows_shoot',
        ),
        migrations.RemoveField(
            model_name='training',
            name='arrows_shoot_b',
        ),
        migrations.RemoveField(
            model_name='training',
            name='arrows_shoot_f',
        ),
        migrations.RemoveField(
            model_name='training',
            name='average_arrow_score',
        ),
        migrations.RemoveField(
            model_name='training',
            name='average_arrow_score_b',
        ),
        migrations.RemoveField(
            model_name='training',
            name='average_arrow_score_f',
        ),
        migrations.RemoveField(
            model_name='training',
            name='counted_arrows',
        ),
        migrations.RemoveField(
            model_name='training',
            name='counted_arrows_b',
        ),
        migrations.RemoveField(
            model_name='training',
            name='counted_arrows_f',
        ),
        migrations.RemoveField(
            model_name='training',
            name='missed_arrows',
        ),
        migrations.RemoveField(
            model_name='training',
            name='missed_arrows_b',
        ),
        migrations.RemoveField(
            model_name='training',
            name='missed_arrows_f',
        ),
        migrations.RemoveField(
            model_name='training',
            name='result_b',
        ),
        migrations.RemoveField(
            model_name='training',
            name='result_f',
        ),
    ]
